import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ImageGrid from './components/ImageGrid.js'

export default function Home() {
  
  const marginBottom = "128";
  return (
    <div className={styles.container}>
      <Head>


        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Custom Lights & Iron
        </h1>
        <p><b>Exceptional ironwork for discriminating lifestyles.</b></p>
      <ImageGrid/>

     
  </main>
      
    </div>
                                        )
                                      }
